### ISSUE TITLE
Server git-as-svn do not start when exist submodules on root of git repo

### ISSUE THREAD

**Issue by valmont2k** [bozaro/git-as-svn#111]
Не стартует сервер  git-as-svn, когда в корне гит репозитория существуют ссылки в виде сабмодулей на другие репозитории. При этом остановка происходит на добавлении ревизий и сервис недоступен. Прекрасно на данном этапе было бы добавить игнорирование сабмодулей. Спасибо за проект.

**Comment by bozaro** [comment]
Логов не хватает.
Что-то подобное я подпирал в a368bb99107d9078d1645e4272db23fbbbbd8ea0
Но с отсутствующими сабмодулями есть проблемы: надо вайпать кэш *.mapdb после заливки в сабмодули ревизий, на которые уже есть ссылки. К сожалению, эта проблема не решена, но я думаю об этом.

**Comment by bozaro** [comment]
Логов до сих пор нет. Без них решить проблему не получится.

**Comment by valmont2k** [comment]
2019-08-19T18:47:22,791  INFO [main] (Main.java:42) - git-as-svn version: 1.21.4, eb609ad480a579183858a87449e435ff166548b8
2019-08-19T18:47:23,555  INFO [main] (Log.java:193) - Logging initialized @1654ms to org.eclipse.jetty.util.log.Slf4jLog
2019-08-19T18:47:23,726  INFO [main] (Server.java:370) - jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 1.8.0_201-b09
2019-08-19T18:47:23,784  INFO [main] (ContextHandler.java:857) - Started o.e.j.s.ServletContextHandler@488d1cd7{/,null,AVAILABLE}
2019-08-19T18:47:23,809  INFO [main] (AbstractConnector.java:292) - Started ServerConnector@3336e6b6{HTTP/1.1,[http/1.1]}{localhost:8123}
2019-08-19T18:47:23,810  INFO [main] (Server.java:410) - Started @1911ms
2019-08-19T18:47:26,535  INFO [main] (GitRepositoryConfig.java:100) - [apopv/testgas]: using existing storage /var/opt/gitlab/git-data/repositories/apopv/testgas.git
2019-08-19T18:47:27,302  INFO [main] (GitRepositoryConfig.java:100) - [apopv/Main]: using existing storage /var/opt/gitlab/git-data/repositories/apopv/Main.git
2019-08-19T18:47:27,495  INFO [main] (GitRepositoryConfig.java:100) - [OceanSplash/Art]: using existing storage /var/opt/gitlab/git-data/repositories/OceanSplash/Art.git
2019-08-19T18:47:27,522  INFO [main] (GitLabProject.java:47) - [apopv/Main]: initing...
2019-08-19T18:47:27,522  INFO [ForkJoinPool.commonPool-worker-1] (GitLabProject.java:47) - [OceanSplash/Art]: initing...
2019-08-19T18:47:27,537  INFO [ForkJoinPool.commonPool-worker-1] (GitBranch.java:207) - [OceanSplash/Art@master]: loading cached revision changes: 843 revisions
2019-08-19T18:47:27,632  INFO [main] (GitBranch.java:207) - [apopv/Main@master]: loading cached revision changes: 6847 revisions
2019-08-19T18:47:27,805  INFO [ForkJoinPool.commonPool-worker-1] (GitBranch.java:219) - [OceanSplash/Art@master]: 843 cached revision loaded: 267 ms
2019-08-19T18:47:36,678 ERROR [main] (ObjectDirectory.java:682) - Exception caught while accessing pack file /var/opt/gitlab/git-data/repositories/apopv/Main.git/objects/pack/pack-38740f42bcc6218e4d1a48498fccd2e3a8570732.pack, the pack file might be corrupt. Caught 1 consecutive errors while trying to read this pack.
java.io.IOException: In-memory buffer limit exceeded
        at org.eclipse.jgit.internal.storage.file.PackFile.load(PackFile.java:911) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.internal.storage.file.PackFile.get(PackFile.java:313) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:488) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:446) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:437) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:165) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.diff.ContentSource$ObjectReaderSource.open(ContentSource.java:145) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.diff.ContentSource$Pair.open(ContentSource.java:282) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.diff.SimilarityRenameDetector.hash(SimilarityRenameDetector.java:387) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.diff.SimilarityRenameDetector.buildMatrix(SimilarityRenameDetector.java:300) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.diff.SimilarityRenameDetector.compute(SimilarityRenameDetector.java:139) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.diff.RenameDetector.findContentRenames(RenameDetector.java:529) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.diff.RenameDetector.compute(RenameDetector.java:406) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at org.eclipse.jgit.diff.RenameDetector.compute(RenameDetector.java:372) ~[org.eclipse.jgit-5.4.0.201906121030-r.jar:5.4.0.201906121030-r]
        at svnserver.repository.git.GitBranch.collectRename(GitBranch.java:392) ~[git-as-svn.jar:?]
        at svnserver.repository.git.GitBranch.loadCacheRevision(GitBranch.java:356) ~[git-as-svn.jar:?]
        at svnserver.repository.git.GitBranch.loadRevisionInfo(GitBranch.java:300) ~[git-as-svn.jar:?]
        at svnserver.repository.git.GitBranch.loadRevisions(GitBranch.java:209) ~[git-as-svn.jar:?]
        at svnserver.repository.git.GitBranch.updateRevisions(GitBranch.java:150) ~[git-as-svn.jar:?]
        at svnserver.ext.gitlab.mapping.GitLabProject.initRevisions(GitLabProject.java:50) ~[git-as-svn.jar:?]
        at svnserver.ext.gitlab.mapping.GitLabMappingConfig.lambda$create$0(GitLabMappingConfig.java:84) ~[git-as-svn.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_201]
        at java.util.concurrent.ConcurrentSkipListMap$ValueSpliterator.forEachRemaining(ConcurrentSkipListMap.java:3447) [?:1.8.0_201]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_201]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_201]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_201]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_201]
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) [?:1.8.0_201]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) [?:1.8.0_201]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) [?:1.8.0_201]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) [?:1.8.0_201]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) [?:1.8.0_201]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_201]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) [?:1.8.0_201]
        at svnserver.ext.gitlab.mapping.GitLabMappingConfig.create(GitLabMappingConfig.java:91) [git-as-svn.jar:?]
        at svnserver.server.SvnServer.<init>(SvnServer.java:149) [git-as-svn.jar:?]
        at svnserver.server.Main.main(Main.java:65) [git-as-svn.jar:?]

**Comment by valmont2k** [comment]
на этом загрузка сервера прерывается, хотя иногда доходит до строки 
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing blob 969905b3fd7fcdf1c54a023c5b9ff97fd5796a10
Удивительно, через 4 года некропощу=)

**Comment by slonopotamus** [comment]
Гугл говорит что ошибка `java.io.IOException: In-memory buffer limit exceeded` в `org.eclipse.jgit.internal.storage.file.PackFile` вызвана нехваткой памяти внутри JVM.

1. Попробуй увеличить `-Xmx` в `/etc/default/git-as-svn`.
2. Если памяти больше нет, стоит попробовать выключить `parallelIndexing` в `/etc/git-as-svn/git-as-svn.conf`

**Comment by valmont2k** [comment]
Действительно, добавил памяти и включил параллельную индексацию и смог сделать чекаут репозитория через свн-клиента со вложенными сабмодулями. Спасибо за помощь.
