### ISSUE TITLE
Kryo is not ThreadSafe 

### ISSUE THREAD

**Issue by fcharlie** [bozaro/git-as-svn#121]
Kryo is not ThreadSafe, mybe CacheRevision should use ThreadLocal<Kryo>
See https://github.com/EsotericSoftware/kryo#threading

**Comment by bozaro** [comment]
Thank you for your attention.

**Comment by slonopotamus** [comment]
We get this after updating to 1.1.3:

`2017-12-08T10:11:49,517 ERROR [main] (Main.java:59) - Fatal error: null
java.lang.ClassCastException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598) ~[?:1.8.0_45]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[?:1.8.0_45]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735) ~[?:1.8.0_45]
	at java.util.concurrent.ConcurrentHashMap.forEachEntry(ConcurrentHashMap.java:4195) ~[?:1.8.0_45]
	at svnserver.repository.mapping.RepositoryListMapping.initRevisions(RepositoryListMapping.java:57) ~[git-as-svn.jar:?]
	at svnserver.server.SvnServer.<init>(SvnServer.java:125) ~[git-as-svn.jar:?]
	at svnserver.server.Main.main(Main.java:48) [git-as-svn.jar:?]
Caused by: java.lang.ClassCastException: org.eclipse.jgit.lib.ObjectId cannot be cast to svnserver.repository.git.cache.CacheChange
	at svnserver.repository.git.GitRepository.lambda$loadRevisionInfo$1(GitRepository.java:382) ~[git-as-svn.jar:?]
	at svnserver.repository.git.GitRepository$$Lambda$29/1321056859.apply(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892) ~[?:1.8.0_45]
	at svnserver.repository.git.GitRepository.loadRevisionInfo(GitRepository.java:379) ~[git-as-svn.jar:?]
	at svnserver.repository.git.GitRepository.loadRevisions(GitRepository.java:209) ~[git-as-svn.jar:?]
	at svnserver.repository.git.GitRepository.updateRevisions(GitRepository.java:352) ~[git-as-svn.jar:?]
	at svnserver.repository.mapping.RepositoryListMapping.lambda$initRevisions$0(RepositoryListMapping.java:59) ~[git-as-svn.jar:?]
	at svnserver.repository.mapping.RepositoryListMapping$$Lambda$27/577127077.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ForEachEntryTask.compute(ConcurrentHashMap.java:4977) ~[?:1.8.0_45]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_45]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_45]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_45]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_45]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_45]
Exception in thread "main" java.lang.ClassCastException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.concurrent.ConcurrentHashMap.forEachEntry(ConcurrentHashMap.java:4195)
	at svnserver.repository.mapping.RepositoryListMapping.initRevisions(RepositoryListMapping.java:57)
	at svnserver.server.SvnServer.<init>(SvnServer.java:125)
	at svnserver.server.Main.main(Main.java:48)
Caused by: java.lang.ClassCastException: org.eclipse.jgit.lib.ObjectId cannot be cast to svnserver.repository.git.cache.CacheChange
	at svnserver.repository.git.GitRepository.lambda$loadRevisionInfo$1(GitRepository.java:382)
	at svnserver.repository.git.GitRepository$$Lambda$29/1321056859.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892)
	at svnserver.repository.git.GitRepository.loadRevisionInfo(GitRepository.java:379)
	at svnserver.repository.git.GitRepository.loadRevisions(GitRepository.java:209)
	at svnserver.repository.git.GitRepository.updateRevisions(GitRepository.java:352)
	at svnserver.repository.mapping.RepositoryListMapping.lambda$initRevisions$0(RepositoryListMapping.java:59)
	at svnserver.repository.mapping.RepositoryListMapping$$Lambda$27/577127077.accept(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap$ForEachEntryTask.compute(ConcurrentHashMap.java:4977)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
`

Either our cache is corrupt (but I failed to understand what git-as-svn version could write data that way) or git-as-svn kryo usage still isn't thread safe enough.

**Comment by slonopotamus** [comment]
Okay, this cannot be explained by cache contents because `svnserver.repository.git.cache.CacheRevision#deserialize` passes `CacheRevision.class` as expected object class to kryo.
