### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by tozor** [bozaro/git-as-svn#124]
Когда одним махом заливается большой объем, выдает ошибку на стадии комита. В /usr/share/git-as-svn/bin/git-as-svn добавил DEFAULT_JVM_OPTS='"-d64" "-Xmx20g"' , не помогло. Вот полный лог ошибки:

> 2017-03-20T14:25:12,893  INFO [pool-2-thread-1] (SvnServer.java:308) - User: andre
2017-03-20T14:25:13,427  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob b5e50548051765cb55828c43200f6ec1240a0551 for file: null
2017-03-20T14:25:13,493  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 014b48666a6d7315c54ef56dda80389162be5eef for file: null
2017-03-20T14:25:13,553  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 45e3d9cad5ba670e0be939740b1009941226c395 for file: null
2017-03-20T14:25:14,396  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob b6829cb7de7f6dbe07f7c3b6665d05119fe75bbf for file: null
2017-03-20T14:25:14,408  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob fb25bb9a649d10bf86838ffb55a65b47963dad2f for file: null
2017-03-20T14:25:14,472  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob eb4f05c05670566fed7c259998b0759c9182f495 for file: null
2017-03-20T14:25:14,478  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob d56f082fa2cb582e4e5add54bfed1244e96b704b for file: null
2017-03-20T14:25:15,063  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 9bedf4d32c215c2e33d79f55cb70edfa2c53827f for file: null
2017-03-20T14:25:15,077  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob b8b9c2b0f73abc14b8d344d60cd07bc623885c68 for file: null
2017-03-20T14:25:15,163  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob ecd68d1e3046d8d17cbfb3434bfaed27353dfd69 for file: null
2017-03-20T14:25:15,171  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob f1595fbd03f10e8215070bc815033da670ad2e0e for file: null
2017-03-20T14:25:15,185  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 0e29a459d72a6fd21d7faf43e90a9e9a730229fe for file: null
2017-03-20T14:25:15,192  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob d6dea3cc05d182ae7eec63b3d2389e5c821945a3 for file: null
2017-03-20T14:25:15,707  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob d5b64791786a6d95fc01250d2c503d763fc4690d for file: null
2017-03-20T14:25:16,074  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob c1697db4d02f26a088be3936a12952fc5fca39c7 for file: null
2017-03-20T14:25:16,118  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 1db37971aed8d2687b5726c47180608cc4f9f489 for file: null
2017-03-20T14:25:16,150  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 2bb7343207ddb50af951805df0e2a30586dcce51 for file: null
2017-03-20T14:25:16,162  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 65362503a1633769998edb9d0b378fefe811fa00 for file: null
2017-03-20T14:25:16,173  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 4e6686d0330317fe6e5c690fb9ae400985ac88d6 for file: null
2017-03-20T14:25:16,301  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob bb447ce6c972d44e6fb652dea3cc53a7fd3b4498 for file: null
2017-03-20T14:25:16,313  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 05e33e8a01b077d5824419cd5afb423aa120d8ef for file: null
2017-03-20T14:25:16,329  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob b25bb87acf22abcceca875a4805563955c9f4dd5 for file: null
2017-03-20T14:25:16,474  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 545a37fb2c6dc913395c77281ac49ef5d4d68069 for file: null
2017-03-20T14:25:16,954  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 84b1d75e295cc1743ee120471bb5e2c71d5acd2a for file: null
2017-03-20T14:25:17,108  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob ef36900d9059151c89977f596ceef51042b16c4d for file: null
2017-03-20T14:25:17,340  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 24da8e02ec4d6b6dfe23c2e8f6ddf546a8967783 for file: null
2017-03-20T14:25:17,352  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 27f456994094392b7804d7b5193f5307e31befb6 for file: null
2017-03-20T14:25:17,372  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob b325fedff13d38a7150c53c585ea011f71cbd55f for file: null
2017-03-20T14:25:17,389  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob b8126296971825c5bdc2ead9ed00d7eee6efc7c4 for file: null
2017-03-20T14:25:17,398  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 4624b18e05d05ac7b89a216357232c6f3e8bae62 for file: null
2017-03-20T14:25:17,408  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob e65d4ec595c143c334a8e59441df3b93451b4349 for file: null
2017-03-20T14:25:17,996  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 543fc233203340b09878b16c93d6462a25a988f8 for file: null
2017-03-20T14:25:18,097  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 05e53d91a4d2ac6b94d5bde9246392c1352777ad for file: null
2017-03-20T14:25:18,106  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 48a2fefa750ea33415d57f5184a9f365c40ac9d9 for file: null
2017-03-20T14:25:18,114  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob ec28256c279ac23584ae8fa9772726d797167d11 for file: null
2017-03-20T14:25:18,222  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob c101fc5711571f5d6e43fa7403c213360921b940 for file: null
2017-03-20T14:25:18,235  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 4de8d42c55a4c8f44d85c2bdb37ca108cf2a295f for file: null
2017-03-20T14:25:18,752  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 7cbc68eb70b2d3b60cead938358b5173e2a52c45 for file: null
2017-03-20T14:25:18,765  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 24eb8e669af4816380a0f60788f7d5285552cf51 for file: null
2017-03-20T14:25:18,869  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 8d585e8cdf095fd3352000bc0a3c89fd9de438e1 for file: null
2017-03-20T14:25:18,881  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob e60b109b8f8316b2bd74733adce1a2b1d30372f5 for file: null
2017-03-20T14:25:18,929  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob d0c625201ae8647f4899a698f6830badd0da1120 for file: null
2017-03-20T14:25:19,542  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 4206caf860b2ea4899ad9bd10742542b59f82bfa for file: null
2017-03-20T14:25:19,647  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 5329aec3a81a3e74a5d1c7e97c0695f9b77123a7 for file: null
2017-03-20T14:25:19,661  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob c4146aa6c353a501aae071ffd6dc3cdbcad73d3b for file: null
2017-03-20T14:25:19,676  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 05457b2f5c2c5e2ad783cd010dabb4b3136271f0 for file: null
2017-03-20T14:25:20,085  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 0a5bef12b7f95e9299434ff05b5f8f5cf2166e1f for file: null
2017-03-20T14:25:20,140  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 5558895eac86ff1e5cfde6d6ab2b521d02606213 for file: null
2017-03-20T14:25:20,152  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob bc703969bf0ad515d1c47bb24e862567aa81e6bd for file: null
2017-03-20T14:25:20,303  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 639d7c4ee909ecfb6c18861312346e9a252f6c98 for file: null
2017-03-20T14:25:21,047  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 9cbc5a0b7d057e3a1a8aac8ded153c37ca16a7f9 for file: null
2017-03-20T14:25:21,192  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob e69e4e68280adcbd56557533b6038aae734ab979 for file: null
2017-03-20T14:25:21,962  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob e176a50b8f23c54e71a843e4836aff16f64a6c49 for file: null
2017-03-20T14:25:22,341  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob ca7b012bac88b397d3151a33d84f395ef410849e for file: null
2017-03-20T14:25:22,359  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 83d20e32581ce0353e7767fe9ba4cf0e27131da6 for file: null
2017-03-20T14:25:22,370  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob f7b4665bd7284eb41f65e7641a702e8e54f4babb for file: null
2017-03-20T14:25:22,381  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob e3e07acb287cf2feea0a3193b39dbdb3c2e35bf1 for file: null
2017-03-20T14:25:22,407  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 6872f9c942dca9cb0de38ed08a2bd30cb1baff46 for file: null
2017-03-20T14:25:22,864  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 7c71be24f3f00abd217752767502af0c083cf88d for file: null
2017-03-20T14:25:22,931  INFO [pool-2-thread-1] (GitDeltaConsumer.java:179) - Created blob 59070f5b18720fbc52c0a2ae6becc9b7abea218b for file: null
2017-03-20T14:25:23,156  WARN [pool-2-thread-1] (CommitCmd.java:630) - Found error in cmd textdelta-end
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236) ~[?:1.8.0_111]
        at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191) ~[?:1.8.0_111]
        at svnserver.TemporaryOutputStream.toInputStream(TemporaryOutputStream.java:123) ~[git-as-svn.jar:?]
        at svnserver.repository.git.GitDeltaConsumer.textDeltaEnd(GitDeltaConsumer.java:176) ~[git-as-svn.jar:?]
        at svnserver.server.command.CommitCmd$EditorPipeline.deltaEnd(CommitCmd.java:512) ~[git-as-svn.jar:?]
        at svnserver.server.command.CommitCmd$EditorPipeline$$Lambda$48/1617013634.processCommand(Unknown Source) ~[?:?]
        at svnserver.server.command.LambdaCmd.process(LambdaCmd.java:46) ~[git-as-svn.jar:?]
        at svnserver.server.command.CommitCmd$EditorPipeline.editorCommand(CommitCmd.java:622) [git-as-svn.jar:?]
        at svnserver.server.command.CommitCmd$EditorPipeline$$Lambda$52/531170403.process(Unknown Source) [git-as-svn.jar:?]
        at svnserver.server.SvnServer.serveClient(SvnServer.java:199) [git-as-svn.jar:?]
        at svnserver.server.SvnServer.lambda$run$14(SvnServer.java:165) [git-as-svn.jar:?]
        at svnserver.server.SvnServer$$Lambda$23/2040142129.run(Unknown Source) [git-as-svn.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
2017-03-20T14:25:23,159  INFO [pool-2-thread-1] (SvnServer.java:172) - Connection from /192.268.13.78:56553 closed
2017-03-20T14:36:25,234  INFO [qtp1279271200-26] (WebServer.java:103) - 127.0.0.1:47134 -  - "POST //localhost:8123/" 200 null

>

**Comment by bozaro** [comment]
А какой характер коммита?
Например:
 - много маленьких файлов;
 - несколько очень больших файлов;
 - много LFS-файлов;
 - несколько LFS-файлов.

**Comment by tozor** [comment]
Много файлов среднего веса. От 180 кб 10 мегабайт. 
![12](https://cloud.githubusercontent.com/assets/6834089/24109137/6ce7aa7c-0d98-11e7-94db-fa7288df9ea2.png)
Подключено к репозиторию гитлаба. Версия гитлаба - 8.17.3, git - 2.10.2 , java 1.8.0_111.

 java -XX:+PrintFlagsFinal 2>&1 | grep MaxHeapSize
    uintx MaxHeapSize                              := 8373927936

**Comment by bozaro** [comment]
А примерный порядок кол-ва файлов?

**Comment by tozor** [comment]
Чем больше размер тем меньше файлов удается закомитить, примерно от 25 до 70

**Comment by bozaro** [comment]
Понятно. При коммите мелкие файлы (до 10Мб) всасываются целиком в память. У крупных хвост за пределами 10 Мб пишется на диск. Но на 70 файлах оно складываться не должно.
Я гляну, что можно сделать и куда девается основная память.

**Comment by vsdev** [comment]
Интересно решение этой проблемы. Есть ли какие-то сведения о баге?

**Comment by vsdev** [comment]
Причина в малом количестве памяти для java процесса при работе с большими репозиториями. Увеличение до 2 Гб решило проблему.

**Comment by slonopotamus** [comment]
Ну и хорошо если решило.
