### ISSUE TITLE
Gitlab oauth causes token confusion

### ISSUE THREAD

**Issue by mkunzecw** [bozaro/git-as-svn#156]
since #155 was implemented a user authenticating using gitlab oauth methods causes an error:

`Exception in thread "pool-2-thread-7" java.lang.IllegalArgumentException: Illegal base64 character a
	at java.util.Base64$Decoder.decode0(java.base@9-internal/Base64.java:714)
	at java.util.Base64$Decoder.decode(java.base@9-internal/Base64.java:526)
	at java.util.Base64$Decoder.decode(java.base@9-internal/Base64.java:549)
	at svnserver.auth.PlainAuthenticator.authenticate(PlainAuthenticator.java:41)
	at svnserver.server.SvnServer.authenticate(SvnServer.java:298)
	at svnserver.server.SessionContext.authenticate(SessionContext.java:78)
	at svnserver.server.SvnServer.serveClient(SvnServer.java:193)
	at svnserver.server.SvnServer.lambda$run$0(SvnServer.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804)`

the same configuration in standalone works fine, maybe the gitlab oauth token is leaked into the svn auth wrongly?

**Comment by slonopotamus** [comment]
This only occurs with native SVN client. It sends \n in the end of auth token while svnkit that we use for tests doesn't. Broken by commit daead0eacca0af280fce57d7c6db98feae2d74d1.
