### ISSUE TITLE
When commit via UiPath I get Error: SharpSvn.SvnRepositoryHookException

### ISSUE THREAD

**Issue by monogiadown** [bozaro/git-as-svn#219]
When I try to commit via UiPath Studio I get back the following error:

Error: SharpSvn.SvnRepositoryHookException: svn: E165001: Invalid svn properties on files:
  /Calculator/Calculator.xaml
Expected:
Actual:
  svn:needs-lock = "*"

----------------
Subversion properties must be consistent with Git config files:
  .gitattributes
  .gitignore
  .tgitconfig

For more detailed information you can see:
 * On English: https://bozaro.github.io/git-as-svn/html/en_US/ch_props.html
 * По-русски: https://bozaro.github.io/git-as-svn/html/ru_RU/ch_props.html

   at UiPath.Studio.Plugin.SourceControl.SVN.SvnSourceControl.<>c__DisplayClass26_0.<CheckInAsync>b__1(ISvnClient client)
   at UiPath.Studio.Plugin.SourceControl.SVN.SvnClientBridge.<>c__DisplayClass17_0.<ExecuteAndMonitorAffectedItemsAsync>b__1()
   at UiPath.Studio.Plugin.SourceControl.SVN.SvnClientBridge.<>c__DisplayClass17_0.<ExecuteAndMonitorAffectedItemsAsync>b__2(ISvnClient _)
   at UiPath.Studio.Plugin.SourceControl.SVN.SvnClientBridge.ThreadSafeExecute[TResult](Func`2 action)
   at UiPath.Studio.Plugin.SourceControl.SVN.SvnClientBridge.<>c__DisplayClass18_0`1.<ExecuteAsync>b__0(CancellationToken _)
   at UiPath.Shared.ProducerConsumerPair.<>c__DisplayClass18_0`1.<StartNew>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Studio.Plugin.SourceControl.SVN.SvnClientBridge.<ExecuteAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Studio.Plugin.SourceControl.SVN.SvnClientBridge.<ExecuteAndMonitorAffectedItemsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Studio.Plugin.SourceControl.SVN.SvnSourceControl.<CheckInAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UiPath.Studio.Plugin.SourceControl.CentralRepositoryUiService.<CheckIn_Execute>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Studio.Plugin.SourceControl.CentralRepositoryUiService.<<get_CheckInCommand>b__17_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Studio.Shared.MVVM.Commands.TaskCommand`3.<Execute>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler), HResult -2146233088

Why this occurs?
Thank you 
Regards
Mono

**Comment by surferPHP** [comment]
Please upload the files

**Comment by monogiadown** [comment]
Hello surferPHP,

Which files do you need?
The UiPath XAML (source code) file?
Are you familiar with UiPath (RPA engine)?

Thank you for the response.

Best Regards

Mono

**Comment by slonopotamus** [comment]
You cannot set `svn:needs-lock = "*"` property because git-as-svn doesn't have support for it.
