### ISSUE TITLE
Tests do not pass with latest Gitea

### ISSUE THREAD

**Issue by slonopotamus** [bozaro/git-as-svn#220]
https://travis-ci.org/bozaro/git-as-svn/jobs/504687639

    2019-03-11T13:30:50,581  WARN [SvnServer-thread-55] (GiteaUserDB.java:88) - User password check error: testuser
    io.gitea.ApiException: Content type "text/html; charset=UTF-8" is not supported for type: class io.gitea.model.User
    	at io.gitea.ApiClient.deserialize(ApiClient.java:725) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at io.gitea.ApiClient.handleResponse(ApiClient.java:920) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at io.gitea.ApiClient.execute(ApiClient.java:847) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at io.gitea.api.UserApi.userGetCurrentWithHttpInfo(UserApi.java:3375) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at io.gitea.api.UserApi.userGetCurrent(UserApi.java:3362) ~[java-gitea-api-1.7.0-SNAPSHOT.jar:?]
    	at svnserver.ext.gitea.auth.GiteaUserDB.check(GiteaUserDB.java:83) ~[main/:?]
    	at svnserver.auth.PlainAuthenticator.authenticate(PlainAuthenticator.java:47) ~[main/:?]
    	at svnserver.server.SvnServer.authenticate(SvnServer.java:306) ~[main/:?]
    	at svnserver.server.SessionContext.authenticate(SessionContext.java:78) ~[main/:?]
    	at svnserver.server.SvnServer.serveClient(SvnServer.java:197) ~[main/:?]
    	at svnserver.server.SvnServer.lambda$run$1(SvnServer.java:172) ~[main/:?]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
    	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by slonopotamus** [comment]
@zeripath

**Comment by zeripath** [comment]
Looking at this right now...
