### ISSUE TITLE
Tests do not pass with latest Gitea

### ISSUE THREAD

**Issue by slonopotamus** [bozaro/git-as-svn#244]
https://travis-ci.org/bozaro/git-as-svn/jobs/528695564#L1902

```
    io.gitea.ApiException: Forbidden
        at io.gitea.ApiClient.handleResponse(ApiClient.java:931)
        at io.gitea.ApiClient.execute(ApiClient.java:847)
        at io.gitea.api.UserApi.userGetCurrentWithHttpInfo(UserApi.java:3375)
        at io.gitea.api.UserApi.userGetCurrent(UserApi.java:3362)
        at svnserver.ext.gitea.GiteaIntegrationTest.createUser(GiteaIntegrationTest.java:181)
        at svnserver.ext.gitea.GiteaIntegrationTest.createUser(GiteaIntegrationTest.java:166)
        at svnserver.ext.gitea.GiteaIntegrationTest.before(GiteaIntegrationTest.java:128)
```

The root of the problem is `userCreateToken` call. `io.gitea.model.AccessToken` has `sha1` field but this is what in fact is returned from Gitea:

```{"id":1,"name":"integration-test","token":"329b7475baafc9a9c6f6ed155c674460417312c9","hashed_token":"","token_last_eight":""}```

So, field is named `token` instead of `sha1`. I dunno whether it is a regression on Gitea side or what. @zeripath? Seems like we need a new release of [java-gitea-api](https://github.com/zeripath/java-gitea-api)?

**Comment by slonopotamus** [comment]
Okay, this is broken by go-gitea/go-sdk#160.

**Comment by zeripath** [comment]
Yeah sorry, I forgot that would break this. I will take a look.

**Comment by techknowlogick** [comment]
I've put a PR to switch field back to sha1.

**Comment by techknowlogick** [comment]
I've just merged the PR that should resolve this. Once drone is finished running CI build this should be remedied. My apologies for breaking this integration. Please @ me if you have any followup on this.

**Comment by slonopotamus** [comment]
No problem, thanks!

**Comment by slonopotamus** [comment]
Tests pass again: https://travis-ci.org/bozaro/git-as-svn/jobs/530704444
