### ISSUE TITLE
GitLab + git-as-svn integration.  301 moved permanently throws exception

### ISSUE THREAD

**Issue by MichaelJCole** [bozaro/git-as-svn#343]
Hi there, I'm getting close!

Ok, so I am working through section 4 now.  Here are my notes (intended for the documentation):

Prerequisites:
1. Read this documentation so you understand how to customize it to your needs.
2. Install GitLab and git-as-svn on Ubuntu 18.04 using debian packages.
3. Verify git-as-svn installation: `svn ls --username test --password test svn://localhost/example/master`
4. Complete GitLab install: Configure root user and a project.
5. Enable git-as-svn for project using topic `git-as-svn:<branch>`.  Project -> Settings -> General -> Topics -> "git-as-svn:master"

Configure GitLab/git-as-svn Integration:
1. Copy [/etc/git-as-svn/git-as-svn.conf from 4.3](https://bozaro.github.io/git-as-svn/htmlsingle/git-as-svn.html#_full_configuration_file_example) to same location on server
2. Get a "Personal Access Token" for root user with all scopes.  `https://[server]/profile/personal_access_tokens`
3. Add token to bottom of `/etc/git-as-svn/git-as-svn.conf`
4. Restart the service.  On Ubuntu, `systemctl restart git-as-svn`
5. Verify the service is back up: `svn ls --username root --password [password] svn://[server]/[group]/[project]/[branch]`

When I try this, here's what I get:

```
$  svn ls --username michael --password "shhhh" svn://teams.project.com/group/repo/master
svn: E170013: Unable to connect to a repository at URL 'svn://teams.project.com/group/repo/master'
svn: E000111: Can't connect to host 'teams.project.com': Connection refused

$  telnet teams.project.com 3690
Trying 1.1.1.1...
telnet: Unable to connect to remote host: Connection refused
```

`journalctl` shows a stack-trace.  Rerunning the svn command doesn't make more stack traces.

It looks like something is using an old URL or isn't following redirects.  I've got to put this down for the rest of the day, but really want it to work.  What do you think?  Thank you!

```
root@ubuntu-18:~# journalctl --no-hostname --no-pager -u git-as-svn.service
-- Logs begin at Wed 2020-04-08 16:34:55 UTC, end at Wed 2020-04-08 17:14:05 UTC. --
Apr 08 16:46:51 systemd[1]: Started git-as-svn server.
Apr 08 16:46:54 git-as-svn[16137]: 2020-04-08T16:46:54,123  INFO [main] (Main.java:43) - git-as-svn version: 1.25.1, e8e223e0ed2f6f3f0fabf03b3fec333ff2944914
Apr 08 16:46:56 git-as-svn[16137]: 2020-04-08T16:46:56,020  INFO [main] (Log.java:169) - Logging initialized @4568ms to org.eclipse.jetty.util.log.Slf4jLog
Apr 08 16:46:56 git-as-svn[16137]: 2020-04-08T16:46:56,489  INFO [main] (Server.java:359) - jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
Apr 08 16:46:56 git-as-svn[16137]: 2020-04-08T16:46:56,663  INFO [main] (ContextHandler.java:825) - Started o.e.j.s.ServletContextHandler@3f57bcad{/,null,AVAILABLE}
Apr 08 16:46:56 git-as-svn[16137]: 2020-04-08T16:46:56,736  INFO [main] (AbstractConnector.java:330) - Started ServerConnector@7fc4780b{HTTP/1.1,[http/1.1]}{localhost:8123} Apr 08 16:46:56 git-as-svn[16137]: 2020-04-08T16:46:56,738  INFO [main] (Server.java:399) - Started @5288ms
Apr 08 16:46:56 git-as-svn[16137]: 2020-04-08T16:46:56,836  INFO [main] (GitRepositoryConfig.java:97) - [example]: storage /var/git/repositories/example.git not found, create mode: EXAMPLE
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,665  INFO [main] (WebServer.java:154) - Registered servlet for path: /example.git/lfs_authenticate
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,669  INFO [main] (WebServer.java:154) - Registered servlet for path: /example.git/info/lfs/objects/*
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,671  INFO [main] (WebServer.java:154) - Registered servlet for path: /example.git/info/lfs/storage/*
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,673  INFO [main] (WebServer.java:154) - Registered servlet for path: /example.git/info/lfs/locks/*
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,773  INFO [main] (GitBranch.java:211) - [example@master]: loading cached revision changes: 1 revisions
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,788  INFO [main] (GitBranch.java:223) - [example@master]: 1 cached revision loaded: 16 ms
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,795  INFO [main] (GitBranch.java:267) - [example@master]: Loading revision changes: 1 revision
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,816  INFO [main] (GitBranch.java:289) - Revision changes loaded: 21 ms
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,833  INFO [main] (GitBranch.java:211) - [example@master]: loading cached revision changes: 1 revisions
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,953  INFO [main] (GitBranch.java:223) - [example@master]: 1 cached revision loaded: 121 ms
Apr 08 16:47:00 git-as-svn[16137]: 2020-04-08T16:47:00,987  INFO [SvnServer] (SvnServer.java:187) - Ready for connections on /0.0.0.0:3690
Apr 08 16:48:25 git-as-svn[16137]: 2020-04-08T16:48:25,265  INFO [SvnServer-thread-2] (SvnServer.java:207) - New connection from: /127.0.0.1:42704
Apr 08 16:48:25 git-as-svn[16137]: 2020-04-08T16:48:25,292  INFO [SvnServer-thread-2] (SvnServer.java:325) - Client: SVN/1.9.7 (x86_64-pc-linux-gnu)
Apr 08 16:48:25 git-as-svn[16137]: 2020-04-08T16:48:25,329  INFO [SvnServer-thread-2] (SvnServer.java:393) - User: $anonymous
Apr 08 16:48:25 git-as-svn[16137]: 2020-04-08T16:48:25,355  INFO [SvnServer-thread-2] (SvnServer.java:273) - Connection from /127.0.0.1:42704 closed
Apr 08 16:57:29 systemd[1]: Stopping git-as-svn server...
Apr 08 16:57:29 git-as-svn[16137]: 2020-04-08T16:57:29,609  INFO [Thread-13] (SvnServer.java:420) - Shutdown server
Apr 08 16:57:29 git-as-svn[16137]: 2020-04-08T16:57:29,615  INFO [SvnServer] (SvnServer.java:194) - Server stopped
Apr 08 16:57:29 git-as-svn[16137]: 2020-04-08T16:57:29,684  INFO [Thread-13] (AbstractConnector.java:380) - Stopped ServerConnector@7fc4780b{HTTP/1.1,[http/1.1]}{localhost:8123}
Apr 08 16:57:29 git-as-svn[16137]: 2020-04-08T16:57:29,691  INFO [Thread-13] (ContextHandler.java:1016) - Stopped o.e.j.s.ServletContextHandler@3f57bcad{/,null,UNAVAILABLE} Apr 08 16:57:29 git-as-svn[16137]: 2020-04-08T16:57:29,696  INFO [Thread-13] (SvnServer.java:415) - Server shutdown complete
Apr 08 16:57:29 systemd[1]: git-as-svn.service: Main process exited, code=exited, status=143/n/a
Apr 08 16:57:29 systemd[1]: git-as-svn.service: Failed with result 'exit-code'.
Apr 08 16:57:29 systemd[1]: Stopped git-as-svn server.
-- Reboot --
Apr 08 17:05:18 systemd[1]: Started git-as-svn server.
Apr 08 17:05:26 git-as-svn[839]: 2020-04-08T17:05:26,105  INFO [main] (Main.java:43) - git-as-svn version: 1.25.1, e8e223e0ed2f6f3f0fabf03b3fec333ff2944914
Apr 08 17:05:29 git-as-svn[839]: 2020-04-08T17:05:29,053  INFO [main] (Log.java:169) - Logging initialized @9901ms to org.eclipse.jetty.util.log.Slf4jLog
Apr 08 17:05:29 git-as-svn[839]: 2020-04-08T17:05:29,613  INFO [main] (Server.java:359) - jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
Apr 08 17:05:29 git-as-svn[839]: 2020-04-08T17:05:29,804  INFO [main] (ContextHandler.java:825) - Started o.e.j.s.ServletContextHandler@432038ec{/,null,AVAILABLE}
Apr 08 17:05:29 git-as-svn[839]: 2020-04-08T17:05:29,860  INFO [main] (AbstractConnector.java:330) - Started ServerConnector@1863d2fe{HTTP/1.1,[http/1.1]}{localhost:8123}
Apr 08 17:05:29 git-as-svn[839]: 2020-04-08T17:05:29,867  INFO [main] (Server.java:399) - Started @10717ms
Apr 08 17:05:30 git-as-svn[839]: 2020-04-08T17:05:30,022  INFO [main] (GitRepositoryConfig.java:100) - [example]: using existing storage /var/git/repositories/example.git
Apr 08 17:05:30 git-as-svn[839]: 2020-04-08T17:05:30,546  INFO [main] (WebServer.java:154) - Registered servlet for path: /example.git/lfs_authenticate
Apr 08 17:05:30 git-as-svn[839]: 2020-04-08T17:05:30,555  INFO [main] (WebServer.java:154) - Registered servlet for path: /example.git/info/lfs/objects/*
Apr 08 17:05:30 git-as-svn[839]: 2020-04-08T17:05:30,556  INFO [main] (WebServer.java:154) - Registered servlet for path: /example.git/info/lfs/storage/*
Apr 08 17:05:30 git-as-svn[839]: 2020-04-08T17:05:30,556  INFO [main] (WebServer.java:154) - Registered servlet for path: /example.git/info/lfs/locks/*
Apr 08 17:05:30 git-as-svn[839]: 2020-04-08T17:05:30,741  INFO [main] (GitBranch.java:211) - [example@master]: loading cached revision changes: 2 revisions
Apr 08 17:05:30 git-as-svn[839]: 2020-04-08T17:05:30,809  INFO [main] (GitBranch.java:223) - [example@master]: 2 cached revision loaded: 69 ms
Apr 08 17:05:30 git-as-svn[839]: 2020-04-08T17:05:30,822  INFO [SvnServer] (SvnServer.java:187) - Ready for connections on /0.0.0.0:3690
Apr 08 17:08:32 systemd[1]: Stopping git-as-svn server...
Apr 08 17:08:32 git-as-svn[839]: 2020-04-08T17:08:32,443  INFO [Thread-13] (SvnServer.java:420) - Shutdown server
Apr 08 17:08:32 git-as-svn[839]: 2020-04-08T17:08:32,448  INFO [SvnServer] (SvnServer.java:194) - Server stopped
Apr 08 17:08:32 git-as-svn[839]: 2020-04-08T17:08:32,472  INFO [Thread-13] (AbstractConnector.java:380) - Stopped ServerConnector@1863d2fe{HTTP/1.1,[http/1.1]}{localhost:8123}
Apr 08 17:08:32 git-as-svn[839]: 2020-04-08T17:08:32,479  INFO [Thread-13] (ContextHandler.java:1016) - Stopped o.e.j.s.ServletContextHandler@432038ec{/,null,UNAVAILABLE}
Apr 08 17:08:32 git-as-svn[839]: 2020-04-08T17:08:32,489  INFO [Thread-13] (SvnServer.java:415) - Server shutdown complete
Apr 08 17:08:32 systemd[1]: git-as-svn.service: Main process exited, code=exited, status=143/n/a
Apr 08 17:08:32 systemd[1]: git-as-svn.service: Failed with result 'exit-code'.
Apr 08 17:08:32 systemd[1]: Stopped git-as-svn server.
Apr 08 17:08:32 systemd[1]: Started git-as-svn server.
Apr 08 17:08:35 git-as-svn[2071]: 2020-04-08T17:08:34,993  INFO [main] (Main.java:43) - git-as-svn version: 1.25.1, e8e223e0ed2f6f3f0fabf03b3fec333ff2944914
Apr 08 17:08:36 git-as-svn[2071]: 2020-04-08T17:08:36,246  INFO [main] (Log.java:169) - Logging initialized @3660ms to org.eclipse.jetty.util.log.Slf4jLog
Apr 08 17:08:36 git-as-svn[2071]: 2020-04-08T17:08:36,621  INFO [main] (Server.java:359) - jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
Apr 08 17:08:36 git-as-svn[2071]: 2020-04-08T17:08:36,727  INFO [main] (ContextHandler.java:825) - Started o.e.j.s.ServletContextHandler@7393222f{/,null,AVAILABLE}
Apr 08 17:08:36 git-as-svn[2071]: 2020-04-08T17:08:36,769  INFO [main] (AbstractConnector.java:330) - Started ServerConnector@651aed93{HTTP/1.1,[http/1.1]}{localhost:8123}
Apr 08 17:08:36 git-as-svn[2071]: 2020-04-08T17:08:36,770  INFO [main] (Server.java:399) - Started @4186ms
Apr 08 17:08:37 git-as-svn[2071]: Exception in thread "main" java.io.UncheckedIOException: org.gitlab.api.GitlabAPIException
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:244)
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:198)
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:166)
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.GitlabAPI.getProjects(GitlabAPI.java:864)
Apr 08 17:08:37 git-as-svn[2071]:         at svnserver.ext.gitlab.mapping.GitLabMappingConfig.create(GitLabMappingConfig.java:79)
Apr 08 17:08:37 git-as-svn[2071]:         at svnserver.server.SvnServer.<init>(SvnServer.java:158)
Apr 08 17:08:37 git-as-svn[2071]:         at svnserver.server.Main.main(Main.java:66)
Apr 08 17:08:37 git-as-svn[2071]: Caused by: org.gitlab.api.GitlabAPIException
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:409)
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.http.GitlabHTTPRequestor.access$300(GitlabHTTPRequestor.java:39)
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:241)
Apr 08 17:08:37 git-as-svn[2071]:         ... 6 more
Apr 08 17:08:37 git-as-svn[2071]: Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
Apr 08 17:08:37 git-as-svn[2071]:  at [Source: (String)"<html>
Apr 08 17:08:37 git-as-svn[2071]: <head><title>301 Moved Permanently</title></head>
Apr 08 17:08:37 git-as-svn[2071]: <body>
Apr 08 17:08:37 git-as-svn[2071]: <center><h1>301 Moved Permanently</h1></center>
Apr 08 17:08:37 git-as-svn[2071]: <hr><center>nginx</center>
Apr 08 17:08:37 git-as-svn[2071]: </body>
Apr 08 17:08:37 git-as-svn[2071]: </html>
Apr 08 17:08:37 git-as-svn[2071]: "; line: 1, column: 2]
Apr 08 17:08:37 git-as-svn[2071]:         at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
Apr 08 17:08:37 git-as-svn[2071]:         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
Apr 08 17:08:37 git-as-svn[2071]:         at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
Apr 08 17:08:37 git-as-svn[2071]:         at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1917)
Apr 08 17:08:37 git-as-svn[2071]:         at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
Apr 08 17:08:37 git-as-svn[2071]:         at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4142)
Apr 08 17:08:37 git-as-svn[2071]:         at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
Apr 08 17:08:37 git-as-svn[2071]:         at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:370)
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.http.GitlabHTTPRequestor.access$200(GitlabHTTPRequestor.java:39)
Apr 08 17:08:37 git-as-svn[2071]:         at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:237)
Apr 08 17:08:37 git-as-svn[2071]:         ... 6 more```

**Comment by slonopotamus** [comment]
git-as-svn tries to talk to GitLab via HTTP API but receives 301 instead. And seems like [java-gitlab-api](https://github.com/timols/java-gitlab-api) that we use to talk to GitLab, doesn't support 301 redirects.

Please verify that you've configured `url:` inside `!gitlab:` section to actual URL where your GitLab is.

**Comment by MichaelJCole** [comment]
Ok, snap.  This might be the "url" setting in the "!gitlab" section.  I set this to `https://teams.project.com/` and now I'm getting what looks like a self-signed cert error.  

I'm not sure why LetsEncrypt was working and now not.  I may have requested too many certs for the same domain recently.  https://letsencrypt.org/docs/rate-limits/

Anyways, I have to work on something else for a bit. 

```
Apr 08 17:42:00 systemd[1]: Stopping git-as-svn server...
Apr 08 17:42:00 systemd[1]: git-as-svn.service: Main process exited, code=exited, status=143/n/a
Apr 08 17:42:00 systemd[1]: git-as-svn.service: Failed with result 'exit-code'.
Apr 08 17:42:00 systemd[1]: Stopped git-as-svn server.
Apr 08 17:42:00 systemd[1]: Started git-as-svn server.
Apr 08 17:42:02 git-as-svn[6021]: 2020-04-08T17:42:02,553  INFO [main] (Main.java:43) - git-as-svn version: 1.25.1, e8e223e0ed2f6f3f0fabf03b3fec333ff2944914
Apr 08 17:42:04 git-as-svn[6021]: 2020-04-08T17:42:04,113  INFO [main] (Log.java:169) - Logging initialized @3063ms to org.eclipse.jetty.util.log.Slf4jLog
Apr 08 17:42:04 git-as-svn[6021]: 2020-04-08T17:42:04,518  INFO [main] (Server.java:359) - jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
Apr 08 17:42:04 git-as-svn[6021]: 2020-04-08T17:42:04,667  INFO [main] (ContextHandler.java:825) - Started o.e.j.s.ServletContextHandler@31add175{/,null,AVAILABLE}
Apr 08 17:42:04 git-as-svn[6021]: 2020-04-08T17:42:04,715  INFO [main] (AbstractConnector.java:330) - Started ServerConnector@bb9e6dc{HTTP/1.1,[http/1.1]}{localhost:8123}
Apr 08 17:42:04 git-as-svn[6021]: 2020-04-08T17:42:04,717  INFO [main] (Server.java:399) - Started @3668ms
Apr 08 17:42:05 git-as-svn[6021]: Exception in thread "main" java.io.UncheckedIOException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:244)
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:198)
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:166)
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.GitlabAPI.getProjects(GitlabAPI.java:864)
Apr 08 17:42:05 git-as-svn[6021]:         at svnserver.ext.gitlab.mapping.GitLabMappingConfig.create(GitLabMappingConfig.java:79)
Apr 08 17:42:05 git-as-svn[6021]:         at svnserver.server.SvnServer.<init>(SvnServer.java:158)
Apr 08 17:42:05 git-as-svn[6021]:         at svnserver.server.Main.main(Main.java:66)
Apr 08 17:42:05 git-as-svn[6021]: Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Apr 08 17:42:05 git-as-svn[6021]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Apr 08 17:42:05 git-as-svn[6021]:         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
Apr 08 17:42:05 git-as-svn[6021]:         at java.security.AccessController.doPrivileged(Native Method)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
Apr 08 17:42:05 git-as-svn[6021]:         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:409)
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.http.GitlabHTTPRequestor.access$300(GitlabHTTPRequestor.java:39)
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:241)
Apr 08 17:42:05 git-as-svn[6021]:         ... 6 more
Apr 08 17:42:05 git-as-svn[6021]: Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:364)
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.http.GitlabHTTPRequestor.access$200(GitlabHTTPRequestor.java:39)
Apr 08 17:42:05 git-as-svn[6021]:         at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:237)
Apr 08 17:42:05 git-as-svn[6021]:         ... 6 more
Apr 08 17:42:05 git-as-svn[6021]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.validator.Validator.validate(Validator.java:262)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
Apr 08 17:42:05 git-as-svn[6021]:         ... 21 more
Apr 08 17:42:05 git-as-svn[6021]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
Apr 08 17:42:05 git-as-svn[6021]:         at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
Apr 08 17:42:05 git-as-svn[6021]:         at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
Apr 08 17:42:05 git-as-svn[6021]:         ... 27 more
root@ubuntu-18:~# journalctl --no-hostname --no-pager -u git-as-svn.service
```

**Comment by slonopotamus** [comment]
Yes, this is a self-signed certificate error.

git-as-svn doesn't currently have an option to disable SSL certificate validation.

But you can import your certificate into JRE so that git-as-svn trusts it. Please, refer to documentation of your exact JVM implementation. Normally, it is just something like [this](https://knowledge.digicert.com/solution/SO4085.html) but I saw cases where JVM was using system certificate directory instead of Java-specific keystore files.

**Comment by MichaelJCole** [comment]
That was it!  Thanks
