### ISSUE TITLE
GitLabIntegrationTest.testLfs fails with GitLab 13.7+

### ISSUE THREAD

**Issue by slonopotamus** [bozaro/git-as-svn#365]
https://github.com/bozaro/git-as-svn/runs/1792413180?check_suite_focus=true#step:5:2021

```
Gradle suite > Gradle test > svnserver.ext.gitlab.GitLabIntegrationTest > testLfs FAILED
    org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at ru.bozaro.gitlfs.client.internal.HttpClientExecutor.executeMethod(HttpClientExecutor.java:27)
        at ru.bozaro.gitlfs.client.Client.doRequest(Client.java:117)
        at ru.bozaro.gitlfs.client.Client.putObject(Client.java:215)
        at svnserver.ext.gitlfs.storage.network.LfsHttpWriter.finish(LfsHttpWriter.java:72)
        at svnserver.ext.gitlfs.storage.local.LfsLocalStorageTest.checkLfs(LfsLocalStorageTest.java:188)
        at svnserver.ext.gitlfs.storage.local.LfsLocalStorageTest.checkLfs(LfsLocalStorageTest.java:145)
        at svnserver.ext.gitlab.GitLabIntegrationTest.testLfs(GitLabIntegrationTest.java:198)

        Caused by:
        org.apache.http.ProtocolException: Transfer-encoding header already present
            at org.apache.http.protocol.RequestContent.process(RequestContent.java:94)
            at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
            at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
            at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
            at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
            at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
            ... 9 more
```

**Comment by slonopotamus** [comment]
Caused by https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48269
