### ISSUE TITLE
LDAP-пользователь без почты не может просматривать репозиторий

### ISSUE THREAD

**Issue by mudlo** [bozaro/git-as-svn#97]
Exception in thread "pool-1-thread-15" java.lang.IllegalStateException: Users without email not allower: qasysuser
	at svnserver.auth.ldap.LdapUserDB.findUser(LdapUserDB.java:156)
	at svnserver.auth.ldap.LdapUserDB.check(LdapUserDB.java:104)
	at svnserver.auth.PlainAuthenticator.authenticate(PlainAuthenticator.java:48)
	at svnserver.server.SvnServer.authenticate(SvnServer.java:280)
	at svnserver.server.SvnServer.serveClient(SvnServer.java:179)
	at svnserver.server.SvnServer.lambda$run$6(SvnServer.java:155)
	at svnserver.server.SvnServer$$Lambda$9/1661983184.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by slonopotamus** [comment]
Regression, introduced in 86e19b45923f9c82f3d8301b477125072358e0c8
